// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY3uEt6C2RiKiNgXVJW-fGryUSKL8_EVM',
    appId: '1:394315006257:web:b01655643baa2930aef010',
    messagingSenderId: '394315006257',
    projectId: 'kaphe-f480c',
    authDomain: 'kaphe-f480c.firebaseapp.com',
    storageBucket: 'kaphe-f480c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqDtqfiUN5EkC8GfCV_fhpWdy08ayvKk',
    appId: '1:394315006257:android:40ae1c76184dcb66aef010',
    messagingSenderId: '394315006257',
    projectId: 'kaphe-f480c',
    storageBucket: 'kaphe-f480c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVZLD6vaxRXiG-by7CKZeZwVzm7UdXNY',
    appId: '1:394315006257:ios:618d53d49ce6f677aef010',
    messagingSenderId: '394315006257',
    projectId: 'kaphe-f480c',
    storageBucket: 'kaphe-f480c.firebasestorage.app',
    androidClientId: '394315006257-3i6bb27nhfh9q7t9o0hvrku47r8ckk7m.apps.googleusercontent.com',
    iosClientId: '394315006257-hnnitolp1i2sl1q6cp7ttmt6k1vr5kur.apps.googleusercontent.com',
    iosBundleId: 'com.example.kapheapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrVZLD6vaxRXiG-by7CKZeZwVzm7UdXNY',
    appId: '1:394315006257:ios:618d53d49ce6f677aef010',
    messagingSenderId: '394315006257',
    projectId: 'kaphe-f480c',
    storageBucket: 'kaphe-f480c.firebasestorage.app',
    androidClientId: '394315006257-3i6bb27nhfh9q7t9o0hvrku47r8ckk7m.apps.googleusercontent.com',
    iosClientId: '394315006257-hnnitolp1i2sl1q6cp7ttmt6k1vr5kur.apps.googleusercontent.com',
    iosBundleId: 'com.example.kapheapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY3uEt6C2RiKiNgXVJW-fGryUSKL8_EVM',
    appId: '1:394315006257:web:654ef93fe730d52baef010',
    messagingSenderId: '394315006257',
    projectId: 'kaphe-f480c',
    authDomain: 'kaphe-f480c.firebaseapp.com',
    storageBucket: 'kaphe-f480c.firebasestorage.app',
  );
}
