// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADhjR2tO24G5ziwNwSycfyuHoatdFzmOI',
    appId: '1:968858113254:web:2e2ce4409d429059681727',
    messagingSenderId: '968858113254',
    projectId: 'kaphe-a1d34',
    authDomain: 'kaphe-a1d34.firebaseapp.com',
    storageBucket: 'kaphe-a1d34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdQSm2KB-pH0ntRAnhKptH3aLGIorl0bM',
    appId: '1:968858113254:android:0e57b5cbbcb3ede4681727',
    messagingSenderId: '968858113254',
    projectId: 'kaphe-a1d34',
    storageBucket: 'kaphe-a1d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBashKQR61TmewcKG_stmWpNOmjd30qe8',
    appId: '1:968858113254:ios:7997c271f459a24e681727',
    messagingSenderId: '968858113254',
    projectId: 'kaphe-a1d34',
    storageBucket: 'kaphe-a1d34.firebasestorage.app',
    androidClientId: '968858113254-uoam48h0re2clifjutflj9d8ouu8jah5.apps.googleusercontent.com',
    iosClientId: '968858113254-9u46urdrte75kge8ecdo7n09q56r8spm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kapheapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBashKQR61TmewcKG_stmWpNOmjd30qe8',
    appId: '1:968858113254:ios:7997c271f459a24e681727',
    messagingSenderId: '968858113254',
    projectId: 'kaphe-a1d34',
    storageBucket: 'kaphe-a1d34.firebasestorage.app',
    androidClientId: '968858113254-uoam48h0re2clifjutflj9d8ouu8jah5.apps.googleusercontent.com',
    iosClientId: '968858113254-9u46urdrte75kge8ecdo7n09q56r8spm.apps.googleusercontent.com',
    iosBundleId: 'com.example.kapheapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADhjR2tO24G5ziwNwSycfyuHoatdFzmOI',
    appId: '1:968858113254:web:5bac3233d0dcd1dc681727',
    messagingSenderId: '968858113254',
    projectId: 'kaphe-a1d34',
    authDomain: 'kaphe-a1d34.firebaseapp.com',
    storageBucket: 'kaphe-a1d34.firebasestorage.app',
  );

}