name: kapheapp
description: "Final year project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core utilities
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.3.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # UI components
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.0.0
  firebase_app_check: 0.3.2+5 # Check for the latest version



  google_sign_in: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  file_picker: ^10.1.2
  cloudinary_sdk: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/beverages/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/on_boarding_images/
    - assets/images/banners/
    - assets/images/locations/
    - assets/user/
    - assets/cafe_brand/
    - assets/animation/

  fonts:
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
    - family: LeagueScript
      fonts:
        - asset: assets/fonts/LeagueScript-Regular.ttf
